# -*- coding: utf-8 -*-
"""Analise_Seis_sigma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rPztIJIoW9bvXqd9L7_Rq0eiu4JFlCqB
"""

# from google.colab import drive
# drive.mount('/content/drive')

"""# 1 - Importando a libs"""

# !pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %reset

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import dateutil.parser
import seaborn as sns
import sklearn
import scipy.stats as stats
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as sm
from sklearn.model_selection import train_test_split
import plotly.express as px
import streamlit as st

"""# 2 - Lendo os dados"""

df = pd.read_excel('/content/drive/MyDrive/datasets/Vale/Produção_CKS.xlsm', sheet_name='Variabilidade', usecols=list(range(5)))

"""# 3 - Entendimento do dados"""

df.info()

"""## 3.1 - Adicionando mês e ano"""

df['mes'] = pd.to_datetime(df['Data']).dt.month
df['ano'] = pd.to_datetime(df['Data']).dt.year

def clima(mes):
    if mes == 1 or mes == 2 or mes == 3 or mes == 4:
        return 'chove'
    elif mes == 11 or mes == 12:
        return 'intermediario'
    elif mes == 6 or mes == 7 or mes == 8 or mes == 9 or mes == 10:
        return 'seco'
    else:
        return 'chove'

# Aplicando a função usando apply e lambda
df['clima'] = df['mes'].apply(lambda x: clima(x))

"""## 3.2 - Calculando a média, o desvio padrão mês a mês e coeficiente de variação"""

df_cv = df.groupby(['ano', 'mes','Sistema produtivo'])['Produção_ajuste'].agg(['mean', 'std']).round(2)
df_cv.columns = ['Média', 'Desvio_Padrão']
df_cv['Coeficiente_var'] = round(df_cv['Desvio_Padrão'] / df_cv['Média'], 4)*100
df_cv = df_cv.reset_index()

df_cv_acumulado = df_cv.groupby(['Sistema produtivo'])['Média'].agg(['mean', 'std']).round(2)
df_cv_acumulado.columns = ['Média', 'Desvio_Padrão']
df_cv_acumulado['Coeficiente_var'] = round(df_cv_acumulado['Desvio_Padrão'] / df_cv_acumulado['Média'], 4)*100
df_cv_acumulado = df_cv_acumulado.reset_index()

df_cv_total = df_cv.groupby(['ano', 'mes'])['Média'].agg(['sum', 'std']).round(2)
df_cv_total.columns = ['Média', 'Desvio_Padrão']
df_cv_total['Coeficiente_var'] = round(df_cv_total['Desvio_Padrão'] / df_cv_total['Média'], 4)*100
df_cv_total = df_cv_total.reset_index()

"""# 4 - Dashboard"""

st.set_page_config(layout="wide")

st.title('Dashboard de Produção')

st.header('Média Mensal de Produção por Sistema Produtivo')
st.dataframe(df_cv.style.background_gradient(cmap='Greens'))

st.header('Média Mensal de Produção Total')
st.dataframe(df_cv_total.style.background_gradient(cmap='Greens'))

st.header('Média Anual de Produção por Sistema Produtivo')
st.dataframe(df_cv_acumulado.style.background_gradient(cmap='Greens'))

st.header('Gráfico de Média Mensal de Produção por Sistema Produtivo')
fig = px.bar(df_cv, x='mes', y='Média', color='Sistema produtivo', barmode='group')
st.plotly_chart(fig)

st.header('Gráfico de Média Mensal de Produção Total')
fig = px.bar(df_cv, x='mes', y='Média', color='Sistema produtivo', barmode='group')
st.plotly_chart(fig)

st.header('Gráfico de Média Anual de Produção por Sistema Produtivo')
fig = px.bar(df_cv_acumulado, x='Sistema produtivo', y='Média', color='Sistema produtivo', barmode='group')
st.plotly_chart(fig)
